language: node_js
sudo: required

branches:
  only:
    - master

services:
  - mongodb
  - docker

install:
  - npm install

jobs:
  include:
    - stage: test
      name: "Unit Tests: Node 6"
      node_js: 6

      before_install:
        - docker pull danielcalvo/orion
        - docker run -d --net host -l orion danielcalvo/orion

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 8"
      node_js: 8

      before_install:
        - docker pull danielcalvo/orion
        - docker run -d --net host -l orion danielcalvo/orion

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 10"
      node_js: 10

      before_install:
        - docker pull danielcalvo/orion
        - docker run -d --net host -l orion danielcalvo/orion

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Documentation Tests"
      node_js: 10

      script:
        - npm run lint:md
        - npm run lint:text
