language: node_js
sudo: required

branches:
  only:
    - master

services:
  - mongodb
  - docker

install:
  # It seems to be a good idea to clean before install
  # see https://travis-ci.community/t/i-needed-an-explicit-cleanup-before-starting-my-tests-to-have-then-working-again-is-that-normal/5512/2
  - npm run clean
  - npm install

jobs:
  include:
    - stage: test
      name: "Unit Tests: Node 10"
      node_js: 10

      before_install:
        - docker pull fiware/orion:latest
        - docker run -d --net host -l orion fiware/orion:latest

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 12"
      node_js: 12

      before_install:
        - docker pull fiware/orion:latest
        - docker run -d --net host -l orion fiware/orion:latest

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 14"
      node_js: 14

      before_install:
        - docker pull fiware/orion:latest
        - docker run -d --net host -l orion fiware/orion:latest

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Documentation Tests"
      node_js: 10

      script:
        - npm run lint:md
        - npm run lint:text

    - stage: test
      name: "Dockerfile Tests"
      language: bash
      install:
        - docker pull hadolint/hadolint
      script:
        - docker run --rm -i hadolint/hadolint < ./docker/Dockerfile

