site_name: Fiware-iotagent-lwm2m
site_url: https://fiware-iotagent-ul.readthedocs.org
repo_url: https://github.com/telefonicaid/iotagent-lwm2m.git
site_description: IoT Agent LWM2M (CoAP/UDP transport) Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs

extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]

pages:

- 'Home': 'index.md'
- 'User & Programmers Manual': 
   - 'Intro & Development guide': 'userGuide.md'
   - 'API Walkthrough & Device provisioning': 'deviceProvisioning.md'
   - 'Operation with Static configuration': 'staticConfiguration.md'
   - 'Operation with Provisioning configuration': 'configurationProvisioning.md'
- 'Installation & Administration Manual': 'administrationGuide.md'
